### PR TITLE
Used newer API

### PR DESCRIPTION
**Pull request by ApCoder123**
`this.features` is deprecated and `this.featuresMap` should be used instead

### CODE REVIEW

**Comment by vmassol** [comment]
It's deprecated but it can still be used. If you remove this code then I guess it won't work anymore, will it?

**Comment by vmassol** [comment]
Ideally it should be moved to the legacy module probably (http://dev.xwiki.org/xwiki/bin/view/Community/DevelopmentPractices#HBackwardCompatibility).

**Comment by ApCoder123** [comment]
@vmassol I checked it out and it turns out that the method `getExtensionFeatures` used to get that features list only uses `this.featuresMap` so it doesn't really matter if we don't set the list any more, as it is never being fetched.

**Comment by tmortagne** [comment]
You did not understand what this method does. It set this.features so that users of getFeatures() method get the right list.

**Pull request closed without merging**
