### PR TITLE
[misc] exclude org.antlr dependency from checkstyle

### PR DESCRIPTION
**Pull request by romani**
problem detected at https://github.com/checkstyle/checkstyle/pull/9025

but we still have problem to run successfully 
`[ERROR] Failed to execute goal on project xwiki-commons-xml: Could not resolve dependencies for project org.xwiki.commons:xwiki-commons-xml:jar:13.0-SNAPSHOT: Failure to find io.sf.carte:xml-dtd:jar:3.1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project xwiki-commons-xml: Could not resolve dependencies for project org.xwiki.commons:xwiki-commons-xml:jar:13.0-SNAPSHOT: Failure to find io.sf.carte:xml-dtd:jar:3.1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced`

@tmortagne , can you help us to find `io.sf.carte:xml-dtd` or howto skip it ?

### CODE REVIEW

**Comment by tmortagne** [comment]
> @tmortagne , can you help us to find io.sf.carte:xml-dtd or howto skip it ?

Checking, if this is not on Maven central it would be a mistake on our side IMO (we are only supposed to depend on Maven Central stuff in xwiki-commons).

**Comment by tmortagne** [comment]
@romani I created https://jira.xwiki.org/browse/XCOMMONS-2094 on out side. Until we fix that it seems that io.sf.carte:xml-dtd Maven repository is https://css4j.github.io/maven.

**Comment by tmortagne** [comment]
On the antlr front it's strange that you have a problem since we upgraded to 4.9 last week.

**Comment by romani** [comment]
Let me recheck, I tried to search upgrade on it your code and didn't not found it.

As we both use Auto dependency upgrade, such excludes might not be required, we can wait for you to upgrade first.

**Comment by romani** [comment]
@tmortagne , problems is reproduced on next antlr update.
as both of us use same service for version bump, it might be time issue which repo got PR quicker, and unfortunately we have to merge version bump after you.
To void this dependency, it might be better to merge this PR and do not depend on each other.

**Comment by romani** [comment]
from our CI:
```
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-upper-bounds) @ xwiki-commons-tool-verification-resources ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for org.antlr:antlr4-runtime:4.8-1 paths to dependency are:
+-org.xwiki.commons:xwiki-commons-tool-verification-resources:12.7-SNAPSHOT
  +-com.puppycrawl.tools:checkstyle:8.40-SNAPSHOT
    +-org.antlr:antlr4-runtime:4.8-1 (managed) <-- org.antlr:antlr4-runtime:4.9.1
and
+-org.xwiki.commons:xwiki-commons-tool-verification-resources:12.7-SNAPSHOT
  +-com.puppycrawl.tools:checkstyle:8.40-SNAPSHOT
    +-org.antlr:antlr4-runtime:4.8-1
```

**Comment by tmortagne** [comment]
OK applying that is not doing any harm anyway.

**Pull request merged**
