### PR TITLE
[misc] exclude commons-beanutils dependency from checkstyle

### PR DESCRIPTION
**Pull request by romani**
to avoid conflict with their too recent version

it will allow to merge - https://github.com/checkstyle/checkstyle/pull/7000 (version bump to resolve security issue in checkstyle)

### CODE REVIEW

**Comment by tmortagne** [comment]
Would make more sense to upgrade beanutils actually. Strangely I did not get any notification for this new beanutils version, otherwise I would have upgraded it.

Taking care of it today. See https://jira.xwiki.org/browse/XCOMMONS-1712.

**Comment by romani** [comment]
It would be probably good to exclude it, if any new version of this library happen it will result in same issue on our side, and will bother you again. Same as we have guava library.

**Comment by tmortagne** [comment]
We tend to upgrade this kind of libraries as soon as they are released but if you are sure it's not needed at build time then sure why not.

**Comment by romani** [comment]
We use only few items from it.
Ok, let's think about it, on next update, it  does not release that often.

**Comment by tmortagne** [comment]
OK you will be able to tell me "I told you so" ;)

**Comment by romani** [comment]
> "I told you so"

@tmortagne , fyi - https://jira.xwiki.org/browse/XCOMMONS-1815

**Comment by tmortagne** [comment]
Not fair, was released just 2 days ago but OK fine :)

**Pull request closed without merging**
